# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 796fc5bc2293bf9d5039093824c071e59ca5b20c00c5f967441ec0569b4424d4796418d4dfa9f034faa03b1a4e43e96b98c4be340570ed5b6d8a086c38c7dcd0

test:
  secret_key_base: e58f35d78aeba8a212814696a9e2f80452c74d8e76e2cb82c04db4e16edb6e37b65ccbedf365f0e1408ac2a84353db09d332783a042fb90b422a786fcc5a5417

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
